import data from './data.json'

const option = {
  animation: true,
  legend: {
    type: 'plain',
    data: data.legend,
    show: true,
    orient: 'horizontal',
    left: '68%',
    top: '0%',
    itemGap: 20,
    textStyle: {
      fontFamily: 'Arial,苹方,微软雅黑',
      fontSize: 16,
      color: '#fff',
      fontWeight: 'normal',
      textShadowBlur: 20,
      textShadowColor: '#4A92EC',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  tooltip: {
    show: true,
    confine: true,
    trigger: 'axis',
    axisPointer: { lineStyle: { color: '#ccc' } },
    triggerOn: 'mousemove',
    borderColor: 'rgba(52,136,167,1)',
    borderWidth: 0,
    backgroundColor: 'rgba(3,43,80,0.8)',
    borderRadius: 0,
    padding: [10, 20, 10, 20],
    textStyle: { color: 'rgba(255,255,255,0.6)', fontSize: 12, fontWeight: 'normal', fontFamily: 'Arial,苹方,微软雅黑' },
    extraCssText: '',
  },
  grid: { left: 20, right: 30, top: 20, bottom: 20, containLabel: true },
  xAxis: {
    type: 'value',
    show: true,
    max: null,
    min: null,
    scale: false,
    splitNumber: null,
    axisLine: { show: true, lineStyle: { color: '#26D9FF', width: 1 } },
    axisTick: { show: true, length: 6, lineStyle: { color: 'rgba(38,217,255,0.5)', width: 2 } },
    splitLine: { show: true, lineStyle: { color: 'rgba(255,255,255,0.2)', width: 1, type: 'dotted' } },
    axisLabel: {
      interval: 0,
      margin: 10,
      fontFamily: 'Arial,苹方,微软雅黑',
      fontSize: 16,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 'normal',
      textShadowBlur: 20,
      textShadowColor: 'rgba(74,146,236,0)',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  yAxis: {
    type: 'category',
    data: data.yAxis,
    show: true,
    axisLine: { show: true, lineStyle: { color: '#26D9FF', width: 1 } },
    splitLine: { show: true, lineStyle: { color: 'rgba(255,255,255,0.2)', width: 1, type: 'dotted' } },
    axisTick: { show: true, length: 5, lineStyle: { color: '#26D9FF', width: 1 } },
    axisLabel: {
      show: true,
      margin: 8,
      rotate: 0,
      fontSize: 16,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 'normal',
      fontFamily: 'Arial,苹方,微软雅黑',
      textShadowBlur: 20,
      textShadowColor: '#4A92EC',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  dataZoom: { orient: 'vertical', type: 'slider', show: false, start: 0, end: 100, left: 10 },
  series: [
    {
      name: '品牌A',
      type: 'bar',
      barWidth: '20%',
      barGap: '30%',
      data: data.series[0],
      itemStyle: {
        borderRadius: 2,
        color: {
          type: 'linear',
          x: 0,
          y: 1,
          x2: 1,
          y2: 0,
          colorStops: [
            { offset: 0, color: 'rgba(61,126,235,0)' },
            { offset: 1, color: 'rgba(61,126,235,1)' },
          ],
          globalCoord: false,
        },
        borderColor: {
          type: 'linear',
          x: 0,
          y: 1,
          x2: 1,
          y2: 0,
          colorStops: [
            { offset: 0, color: '#004FE7' },
            { offset: 1, color: '#7BA7FF' },
          ],
          globalCoord: false,
        },
        borderWidth: 2,
      },
      label: {
        show: true,
        position: 'right',
        distance: 5,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'normal',
        fontFamily: 'Arial,苹方,微软雅黑',
        backgroundColor: 'rgba(255,255,255,0)',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: 'rgba(0,0,0,0)',
        textShadowBlur: 0,
        textShadowColor: '#4A92EC',
        textShadowOffsetX: 0,
        textShadowOffsetY: 0,
        padding: [0, 0, 0, 0],
      },
    },
    {
      name: '品牌B',
      type: 'bar',
      barWidth: '20%',
      barGap: '30%',
      data: data.series[1],
      itemStyle: {
        borderRadius: 2,
        color: {
          type: 'linear',
          x: 0,
          y: 1,
          x2: 1,
          y2: 0,
          colorStops: [
            { offset: 0, color: 'rgba(15,197,243,0)' },
            { offset: 1, color: 'rgba(15,197,243,1)' },
          ],
          globalCoord: false,
        },
        borderColor: {
          type: 'linear',
          x: 0,
          y: 1,
          x2: 1,
          y2: 0,
          colorStops: [
            { offset: 0, color: '#0FC5F3' },
            { offset: 1, color: '#B2EFFF' },
          ],
          globalCoord: false,
        },
        borderWidth: 2,
      },
      label: {
        show: true,
        position: 'right',
        distance: 5,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'normal',
        fontFamily: 'Arial,苹方,微软雅黑',
        backgroundColor: 'rgba(255,255,255,0)',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: 'rgba(0,0,0,0)',
        textShadowBlur: 0,
        textShadowColor: '#4A92EC',
        textShadowOffsetX: 0,
        textShadowOffsetY: 0,
        padding: [0, 0, 0, 0],
      },
    },
  ],
}

export const getOption = (data) => {
  return option
}
