import data from './data.json'

const option = {
  animation: true,
  legend: {
    type: 'plain',
    data: data.legend,
    show: true,
    orient: 'horizontal',
    left: '72%',
    top: '1%',
    itemGap: 30,
    textStyle: {
      fontFamily: 'Arial,苹方,微软雅黑',
      fontSize: 16,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 'normal',
      textShadowBlur: 20,
      textShadowColor: '#4A92EC',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  tooltip: {
    show: true,
    confine: true,
    trigger: 'axis',
    axisPointer: {
      lineStyle: {
        color: '#ccc',
      },
    },
    triggerOn: 'mousemove',
    borderColor: 'rgba(52,136,167,1)',
    borderWidth: 0,
    backgroundColor: 'rgba(3,43,80,0.8)',
    borderRadius: 0,
    padding: [10, 20, 10, 20],
    textStyle: {
      color: 'rgba(255,255,255,0.6)',
      fontSize: 12,
      fontWeight: 'normal',
      fontFamily: 'Arial,苹方,微软雅黑',
    },
    extraCssText: '',
  },
  grid: {
    left: 10,
    right: 10,
    top: 60,
    bottom: 10,
    containLabel: true,
  },
  xAxis: {
    type: 'category',
    show: true,
    data: data.xAxis,
    axisLine: {
      show: true,
      lineStyle: {
        color: '#26D9FF',
        width: 1,
      },
    },
    axisTick: {
      show: true,
      length: 5,
      lineStyle: {
        color: '#26D9FF',
        width: 1,
      },
    },
    splitLine: {
      show: true,
      lineStyle: {
        color: 'rgba(255,255,255,0.2)',
        width: 1,
        type: 'dotted',
      },
    },
    axisLabel: {
      show: true,
      interval: 0,
      rotate: 0,
      margin: 8,
      fontFamily: 'Arial,苹方,微软雅黑',
      fontSize: 16,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 'normal',
      textShadowBlur: 20,
      textShadowColor: '#4A92EC',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  yAxis: {
    type: 'value',
    show: true,
    max: null,
    min: null,
    splitNumber: null,
    scale: false,
    axisLine: {
      show: true,
      lineStyle: {
        color: '#26D9FF',
        width: 1,
      },
    },
    splitLine: {
      show: true,
      lineStyle: {
        color: 'rgba(255,255,255,0.2)',
        width: 1,
        type: 'dotted',
      },
    },
    axisTick: {
      show: true,
      length: 6,
      lineStyle: {
        color: 'rgba(38,217,255,0.5)',
        width: 2,
      },
    },
    axisLabel: {
      show: true,
      margin: 10,
      fontSize: 16,
      color: 'rgba(255,255,255,0.6)',
      fontWeight: 'normal',
      fontFamily: 'Arial,苹方,微软雅黑',
      textShadowBlur: 20,
      textShadowColor: 'rgba(74,146,236,0)',
      textShadowOffsetX: 0,
      textShadowOffsetY: 0,
    },
  },
  dataZoom: {
    type: 'slider',
    show: false,
    start: 0,
    end: 100,
  },
  series: [
    {
      name: 'A区',
      type: 'bar',
      barWidth: '20%',
      barGap: '30%',
      data: data.series[0],
      itemStyle: {
        width: 50,
        borderRadius: 2,
        color: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            {
              offset: 0,
              color: '#3D7EEB',
            },
            {
              offset: 1,
              color: 'rgba(61,126,235,0)',
            },
          ],
          globalCoord: false,
        },
        borderColor: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            {
              offset: 0,
              color: '#A0C4FF',
            },
            {
              offset: 1,
              color: '#3D7EEB',
            },
          ],
          globalCoord: false,
        },
        borderWidth: 2,
      },
      label: {
        show: true,
        position: 'top',
        distance: 5,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'normal',
        fontFamily: 'Arial,苹方,微软雅黑',
        backgroundColor: 'rgba(255,255,255,0)',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: 'rgba(0,0,0,0)',
        textShadowBlur: 0,
        textShadowColor: '#4A92EC',
        textShadowOffsetX: 0,
        textShadowOffsetY: 0,
        padding: [0, 0, 0, 0],
      },
    },
    {
      name: 'B区',
      type: 'bar',
      barWidth: '20%',
      barGap: '30%',
      data: data.series[1],
      itemStyle: {
        width: 50,
        borderRadius: 2,
        color: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            {
              offset: 0,
              color: '#0FC5F3',
            },
            {
              offset: 1,
              color: 'rgba(15,197,243,0)',
            },
          ],
          globalCoord: false,
        },
        borderColor: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            {
              offset: 0,
              color: '#B4F0FF',
            },
            {
              offset: 1,
              color: '#0FC5F3',
            },
          ],
          globalCoord: false,
        },
        borderWidth: 2,
      },
      label: {
        show: true,
        position: 'top',
        distance: 5,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'normal',
        fontFamily: 'Arial,苹方,微软雅黑',
        backgroundColor: 'rgba(255,255,255,0)',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: 'rgba(0,0,0,0)',
        textShadowBlur: 0,
        textShadowColor: '#4A92EC',
        textShadowOffsetX: 0,
        textShadowOffsetY: 0,
        padding: [0, 0, 0, 0],
      },
    },
  ],
}
export default option
